set -e
true
true
/usr/local/bin/spades-core /home/araeedy/pipeline/myrepo/SRR5660000_assembly/K77/configs/config.info
/usr/local/bin/spades-core /home/araeedy/pipeline/myrepo/SRR5660000_assembly/K99/configs/config.info
/usr/local/bin/spades-core /home/araeedy/pipeline/myrepo/SRR5660000_assembly/K127/configs/config.info
/usr/bin/python /usr/local/share/spades/spades_pipeline/scripts/copy_files.py /home/araeedy/pipeline/myrepo/SRR5660000_assembly/K127/before_rr.fasta /home/araeedy/pipeline/myrepo/SRR5660000_assembly/before_rr.fasta /home/araeedy/pipeline/myrepo/SRR5660000_assembly/K127/assembly_graph_after_simplification.gfa /home/araeedy/pipeline/myrepo/SRR5660000_assembly/assembly_graph_after_simplification.gfa /home/araeedy/pipeline/myrepo/SRR5660000_assembly/K127/final_contigs.fasta /home/araeedy/pipeline/myrepo/SRR5660000_assembly/contigs.fasta /home/araeedy/pipeline/myrepo/SRR5660000_assembly/K127/first_pe_contigs.fasta /home/araeedy/pipeline/myrepo/SRR5660000_assembly/first_pe_contigs.fasta /home/araeedy/pipeline/myrepo/SRR5660000_assembly/K127/strain_graph.gfa /home/araeedy/pipeline/myrepo/SRR5660000_assembly/strain_graph.gfa /home/araeedy/pipeline/myrepo/SRR5660000_assembly/K127/scaffolds.fasta /home/araeedy/pipeline/myrepo/SRR5660000_assembly/scaffolds.fasta /home/araeedy/pipeline/myrepo/SRR5660000_assembly/K127/scaffolds.paths /home/araeedy/pipeline/myrepo/SRR5660000_assembly/scaffolds.paths /home/araeedy/pipeline/myrepo/SRR5660000_assembly/K127/assembly_graph_with_scaffolds.gfa /home/araeedy/pipeline/myrepo/SRR5660000_assembly/assembly_graph_with_scaffolds.gfa /home/araeedy/pipeline/myrepo/SRR5660000_assembly/K127/assembly_graph.fastg /home/araeedy/pipeline/myrepo/SRR5660000_assembly/assembly_graph.fastg /home/araeedy/pipeline/myrepo/SRR5660000_assembly/K127/final_contigs.paths /home/araeedy/pipeline/myrepo/SRR5660000_assembly/contigs.paths
true
/usr/bin/python /usr/local/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /home/araeedy/pipeline/myrepo/SRR5660000_assembly/scaffolds.fasta --misc_dir /home/araeedy/pipeline/myrepo/SRR5660000_assembly/misc --threshold_for_breaking_scaffolds 3
true
